defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: |
            gem update --system
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2e:dc:8b:e0:5d:48:5b:74:57:fe:08:8c:dc:57:4f:74"
      - attach_workspace:
          at: ./
      - run:
          name: Upload to FTP
          command: scp -o StrictHostKeyChecking=no -r ./_site/* $USERNAME@$SERVER:$PATH_ON_SERVER
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master